stages:
- test
- deploy

test:lint-and-build:
  stage: test
  image: node:14.17.5
  tags: [dot]
  cache:
    paths:
    - node_modules
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^dev$|^develop$|^development$|^staging$|^master$|^main$|^dev-.*$|^develop-.*$|^development-.*$|^staging-.*$/i'
  before_script:
  - cp .env.example .env.local
  - npm install
  script:
  - npm run lint
  - npm run build

deploy_develop:
  stage: deploy
  image: quay.io/kudaliar032/ansible:2.9.21
  tags: [dot]
  only: [develop]
  when: manual
  environment:
    name: develop
    url: http://pamacapex-dev.dot.co.id
  before_script:
  - chmod 600 $ANSIBLE_KEY_FILE
  script:
  - ansible-playbook --private-key $ANSIBLE_KEY_FILE -i deploy/hosts -v deploy/develop.yaml
