export const accruedStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  APPROVED: 'APPROVED',
  REVISED: 'REVISED',
  REJECTED: 'REJECTED',
  FINAL: 'FINAL',
};
